project:
  type: book

book:
  title: "projects"
  author: "Norah Jones"
  date: "6/29/2025"
  chapters:
    - index.qmd
    - part: "MiniPost"
      chapters:
      - minipost/intro.qmd
      - minipost/overview.qmd
      - minipost/plan.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

number-depth: 1



